base_url = "https://gutenberg-hyde.netlify.com"
compile_sass = true
title = "Hyde theme"
description = "A clean blogging theme"

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_date_format = "%d.%m.%Y"
hyde_theme = ""
# hyde_theme = "theme-base-08"
# hyde_theme = "theme-base-09"
# hyde_theme = "theme-base-0a"
# hyde_theme = "theme-base-0b"
# hyde_theme = "theme-base-0c"
# hyde_theme = "theme-base-0d"
# hyde_theme = "theme-base-0e"
# hyde_theme = "theme-base-0f"
hyde_links = [
    {url = "https://google.com", name = "About"},
]
