name = "hyde-revamped"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/NyxCode/hyde-revamped"
min_version = "0.4"

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_links = []
hyde_date_format = "%d.%m.%Y"
hyde_theme = ""
# hyde_theme = "theme-base-08"
# hyde_theme = "theme-base-09"
# hyde_theme = "theme-base-0a"
# hyde_theme = "theme-base-0b"
# hyde_theme = "theme-base-0c"
# hyde_theme = "theme-base-0d"
# hyde_theme = "theme-base-0e"
# hyde_theme = "theme-base-0f"

[author]
name = "NyxCode"
homepage = "https://github.com/NyxCode/"

[original]
author = "Vincent Prouillet"
homepage = "https://vincent.is"
repo = "https://www.github.com/Keats/hyde"
